//! `handler` — multi-path WASI Preview 2 wasi:http/incoming-handler.
//!
//! Used by Phase E L1–L10 integration tests. Implemented in Rust with
//! `wit-bindgen 0.45` (the version wasmtime 25.0.3 transitively pulls in).
//!
//! ## Paths
//!
//! | Path                          | Behavior                                    |
//! |-------------------------------|---------------------------------------------|
//! | `GET /`                       | 200, body `{"hello":"handler","path":"/"}`  |
//! | `GET /busy`                   | Busy-loops for ~5s, then 200                |
//! | `GET /env/{key}`              | process.get-env(key) → 200 with value       |
//! | `GET /time/now`               | time.now() → 200 with timestamp             |
//! | `GET /kv/set?key=x&val=y`     | kv-store.set(x, y) → 200 "ok"               |
//! | `GET /kv/get?key=x`           | kv-store.get(x) → 200 with value            |
//! | `GET /kv/del?key=x`           | kv-store.delete(x) → 200 "ok"               |
//! | `GET /cache/set?key=x&val=y`  | cache.set(x, y) → 200 "ok"                  |
//! | `GET /cache/get?key=x`        | cache.get(x) → 200 with value               |
//! | `GET /cache/del?key=x`        | cache.delete(x) → 200 "ok"                  |
//! | `GET /log?msg=hello`          | observe.emit-log("info", msg, []) → 200     |
//! | `GET /sockets/tcp/connect?ip=A.B.C.D&port=N` | wasi:sockets tcp-create-socket + start-connect → 200 body "allow" on Ok / "deny:<error>" on Err |
//! | `GET /sockets/udp/bind?ip=A.B.C.D&port=N`    | wasi:sockets udp-create-socket + start-bind → same body shape; exercises `UdpBind` socket-use variant. UDP `send` is exercised only in unit tests (issue #309 tests in `edge-runtime/src/socket_egress.rs` cover `UdpConnect`/`UdpOutgoingDatagram`). |
//! | `GET /sockets/dns-resolve-and-connect?host=NAME&port=N` | wasi:sockets/ip-name-lookup.resolve-addresses → resolve-next-address → start-connect → 200 body with `"ok:"` (closure permitted + connect allowed) or `"deny:<error-code>"`. Exercised by the L51 / L52 `HostnamePinned` integration tests (issue #309 follow-up). The path always uses `AddressFamily::Ipv4`; the IP is whatever the resolver returned. **Today the path runs even though `HostnamePinned` is dormant** — `resolve_addresses` is not gated by the runtime's resolve hook (see `docs/upstream-wasmtime-resolve-check.patch`). The connect side is gated: under `BlockAll`/`HostnamePinned` (empty cache) the start-connect closure returns `false` and the body is `"deny:access-denied"`. |
//! | `GET /sched/once?ms=60000`    | scheduling.schedule-once(ms, []) → 200      |
//!
//! All other paths return 404.

#![no_main]

wit_bindgen::generate!({
    world: "edge-runtime-handler",
    path: "../wit",
    generate_all,
});

use crate::exports::wasi::http::incoming_handler::Guest;
use crate::wasi::http::types::{
    Fields, IncomingRequest, Method, OutgoingResponse, ResponseOutparam,
};

// `wasi:sockets` bindings — generated by wit-bindgen's `generate_all`.
// The path mirrors the WIT package `wasi:sockets@0.2.1` (one Rust
// module per interface under the package). Each `start-connect`/
// `send` call goes through the `WasiSocketsCtx::socket_addr_check`
// closure installed by `edge-runtime::build_wasi_ctx_for_tenant`,
// which is the policy surface hardened by GitHub issue #309.
use crate::wasi::sockets::instance_network::instance_network;
use crate::wasi::sockets::network::{
    ErrorCode as SockErrorCode, IpAddressFamily, IpSocketAddress, Ipv4Address,
    Ipv4SocketAddress,
};
use crate::wasi::sockets::tcp_create_socket::create_tcp_socket;
use crate::wasi::sockets::udp_create_socket::create_udp_socket;
// `wasi:sockets/ip-name-lookup` — generated by wit-bindgen's
// `generate_all`. Used by `/sockets/dns-resolve-and-connect` (issue
// #309 follow-up, exercises the runtime's resolve hook once the
// upstream wasmtime-wasi patch merges).
use crate::wasi::sockets::ip_name_lookup::{
    resolve_addresses, ResolveAddressStream,
};
// `wasi:io/poll` — used to wait for the resolve stream to settle
// before calling `resolve_next_address`. `resolve-next-address` is
// non-blocking in WIT Preview 2: it returns `would-block` if the
// resolver hasn't finished. The contract is "subscribe to the
// stream's `Pollable`, then call `poll::poll` (which blocks) on the
// list, then re-call `resolve_next_address`."
use crate::wasi::io::poll;

// Edge cloud interface imports — available via generate_all.
use crate::edge::cloud::kv_store;
use crate::edge::cloud::cache;
use crate::edge::cloud::process;
use crate::edge::cloud::time;
use crate::edge::cloud::observe;
use crate::edge::cloud::scheduling;

struct Component;
export!(Component);

impl crate::exports::wasi::cli::run::Guest for Component {
    fn run() -> Result<(), ()> {
        unreachable!("wasi:cli/run should not be called for a FaaS component")
    }
}

impl Guest for Component {
    fn handle(req: IncomingRequest, out: ResponseOutparam) {
        let full_path = req.path_with_query().unwrap_or_else(|| "/".to_string());
        let method = req.method();

        // Split path and query string.
        let (path, query) = match full_path.split_once('?') {
            Some((p, q)) => (p, q),
            None => (&full_path[..], ""),
        };

        if !matches!(method, Method::Get) {
            return_json(out, 405, br#"{"error":"method not allowed"}"#);
            return;
        }

        match path {
            "/" => {
                return_json(out, 200, br#"{"hello":"handler","path":"/"}"#);
            }
            "/busy" => {
                return_busy_then_ok(out);
            }
            // ── process ─────────────────────────────────────────────────
            p if p.starts_with("/env/") => {
                let key = &p[5..];
                let val = process::get_env(key);
                match val {
                    Some(v) => return_text(out, 200, v.as_bytes()),
                    None => return_text(out, 404, b"env var not found"),
                }
            }
            "/env" => {
                let all = process::get_all_env();
                let json = serde_json::to_string(&all).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/args" => {
                let args = process::get_args();
                let json = serde_json::to_string(&args).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/cwd" => {
                match process::get_cwd() {
                    Ok(p) => return_text(out, 200, p.as_bytes()),
                    Err(e) => return_text(out, 500, e.as_bytes()),
                }
            }
            // ── time ──────────────────────────────────────────────────
            "/time/now" => {
                let now = time::now();
                let body = format!("{now}");
                return_text(out, 200, body.as_bytes());
            }
            "/time/sleep" => {
                let ms: u64 = get_query_param(query, "ms")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(5);
                time::sleep(ms);
                return_text(out, 200, b"ok");
            }
            "/time/resolution" => {
                let r = time::resolution();
                let body = format!("{r}");
                return_text(out, 200, body.as_bytes());
            }
            // ── kv-store ──────────────────────────────────────────────
            "/kv/set" => {
                let key = get_query_param(query, "key").unwrap_or("");
                let val = get_query_param(query, "val").unwrap_or("");
                let ttl: Option<u32> = get_query_param(query, "ttl")
                    .and_then(|v| v.parse().ok());
                kv_store::set(key, val.as_bytes(), ttl);
                return_text(out, 200, b"ok");
            }
            "/kv/get" => {
                let key = get_query_param(query, "key").unwrap_or("");
                match kv_store::get(key) {
                    Some(data) => return_bytes(out, 200, &data),
                    None => return_text(out, 404, b"key not found"),
                }
            }
            "/kv/del" => {
                let key = get_query_param(query, "key").unwrap_or("");
                kv_store::delete(key);
                return_text(out, 200, b"ok");
            }
            "/kv/exists" => {
                let key = get_query_param(query, "key").unwrap_or("");
                let ok = kv_store::exists(key);
                return_text(out, 200, if ok { b"true" } else { b"false" });
            }
            "/kv/list" => {
                let prefix = get_query_param(query, "prefix").unwrap_or("");
                let keys = kv_store::list_keys(prefix);
                let json = serde_json::to_string(&keys).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/kv/clear" => {
                kv_store::clear();
                return_text(out, 200, b"ok");
            }
            "/kv/get-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                let vals = kv_store::get_many(&keys);
                let strings: Vec<Option<String>> = vals
                    .into_iter()
                    .map(|opt| opt.map(|v| String::from_utf8_lossy(&v).into_owned()))
                    .collect();
                let json = serde_json::to_string(&strings).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/kv/set-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                let vals = split_csv(get_query_param(query, "vals").unwrap_or(""));
                let items: Vec<(String, Vec<u8>, Option<u32>)> = keys
                    .into_iter()
                    .zip(vals.into_iter())
                    .map(|(k, v)| (k, v.into_bytes(), None))
                    .collect();
                kv_store::set_many(&items);
                return_text(out, 200, b"ok");
            }
            "/kv/del-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                kv_store::delete_many(&keys);
                return_text(out, 200, b"ok");
            }
            // ── cache ─────────────────────────────────────────────────
            "/cache/set" => {
                let key = get_query_param(query, "key").unwrap_or("");
                let val = get_query_param(query, "val").unwrap_or("");
                let ttl: Option<u32> = get_query_param(query, "ttl")
                    .and_then(|v| v.parse().ok());
                cache::set(key, val.as_bytes(), ttl);
                return_text(out, 200, b"ok");
            }
            "/cache/get" => {
                let key = get_query_param(query, "key").unwrap_or("");
                match cache::get(key) {
                    Some(data) => return_bytes(out, 200, &data),
                    None => return_text(out, 404, b"key not found"),
                }
            }
            "/cache/del" => {
                let key = get_query_param(query, "key").unwrap_or("");
                cache::delete(key);
                return_text(out, 200, b"ok");
            }
            "/cache/exists" => {
                let key = get_query_param(query, "key").unwrap_or("");
                let ok = cache::exists(key);
                return_text(out, 200, if ok { b"true" } else { b"false" });
            }
            "/cache/list" => {
                let prefix = get_query_param(query, "prefix").unwrap_or("");
                let keys = cache::list_keys(prefix);
                let json = serde_json::to_string(&keys).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/cache/size" => {
                let n = cache::size();
                let body = format!("{n}");
                return_text(out, 200, body.as_bytes());
            }
            "/cache/clear" => {
                cache::clear();
                return_text(out, 200, b"ok");
            }
            "/cache/get-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                let vals = cache::get_many(&keys);
                let strings: Vec<Option<String>> = vals
                    .into_iter()
                    .map(|opt| opt.map(|v| String::from_utf8_lossy(&v).into_owned()))
                    .collect();
                let json = serde_json::to_string(&strings).unwrap_or_else(|_| "[]".to_string());
                return_text(out, 200, json.as_bytes());
            }
            "/cache/set-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                let vals = split_csv(get_query_param(query, "vals").unwrap_or(""));
                let items: Vec<(String, Vec<u8>, Option<u32>)> = keys
                    .into_iter()
                    .zip(vals.into_iter())
                    .map(|(k, v)| (k, v.into_bytes(), None))
                    .collect();
                cache::set_many(&items);
                return_text(out, 200, b"ok");
            }
            "/cache/del-many" => {
                let keys = split_csv(get_query_param(query, "keys").unwrap_or(""));
                cache::delete_many(&keys);
                return_text(out, 200, b"ok");
            }
            // ── observe ───────────────────────────────────────────────
            "/log" => {
                let msg = get_query_param(query, "msg").unwrap_or("no message");
                observe::emit_log("info", msg, &[]);
                return_text(out, 200, b"ok");
            }
            "/observe/counter" => {
                let name = get_query_param(query, "name").unwrap_or("test");
                let val: u64 = get_query_param(query, "val")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(1);
                for _ in 0..val {
                    observe::increment_counter(name, &[]);
                }
                return_text(out, 200, b"ok");
            }
            "/observe/gauge" => {
                let name = get_query_param(query, "name").unwrap_or("test");
                let val: f64 = get_query_param(query, "val")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(0.0);
                observe::record_gauge(name, val, &[]);
                return_text(out, 200, b"ok");
            }
            "/observe/histogram" => {
                let name = get_query_param(query, "name").unwrap_or("test");
                let val: f64 = get_query_param(query, "val")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(0.0);
                observe::record_histogram(name, val, &[]);
                return_text(out, 200, b"ok");
            }
            // ── scheduling ────────────────────────────────────────────
            "/sched/once" => {
                let ms: u64 = get_query_param(query, "ms")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(60_000);
                let id = scheduling::schedule_once(ms, b"");
                return_text(out, 200, id.as_bytes());
            }
            "/sched/repeat" => {
                let ms: u64 = get_query_param(query, "ms")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(60_000);
                let id = scheduling::schedule_repeating(ms, b"");
                return_text(out, 200, id.as_bytes());
            }
            "/sched/cancel" => {
                let id = get_query_param(query, "id").unwrap_or("");
                scheduling::cancel_scheduled(id);
                return_text(out, 200, b"ok");
            }
            // ── SSE / streaming ────────────────────────────────────
            "/sse" => {
                let count: usize = get_query_param(query, "count")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(5);

                let headers = Fields::new();
                let _ = headers.set("content-type", &[b"text/event-stream".to_vec()]);
                let _ = headers.set("cache-control", &[b"no-cache".to_vec()]);
                let resp = OutgoingResponse::new(headers);
                resp.set_status_code(200).unwrap();
                let body_handle = resp.body().expect("response body");
                let stream = body_handle.write().expect("output stream");

                // Deliver headers immediately — the host starts serving
                // the response while we continue writing body chunks.
                ResponseOutparam::set(out, Ok(resp));

                for i in 0..count {
                    let msg = format!("id: {}\ndata: {{\"event\":{}}}\n\n", i, i);
                    stream.blocking_write_and_flush(msg.as_bytes()).unwrap();
                }
                let _ =
                    crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
            }
            // ── wasi:sockets — exercised for issue #309 socket-egress ─
            //
            // Each path constructs the IP literal from query params
            // (or the hard-deny defaults) and walks the corresponding
            // wasi:sockets API. A deny from the runtime's
            // `WasiCtxBuilder::socket_addr_check` closure surfaces as a
            // `Result::Err(ErrorCode)` before any actual TCP/UDP IO;
            // we serialize the error-code variant name in the response
            // body so the test asserts against a stable string.
            "/sockets/tcp/connect" => {
                let ip = get_query_param(query, "ip").unwrap_or("127.0.0.1");
                let port: u16 = get_query_param(query, "port")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(80);
                return_text(out, 200, &socket_call_string(ip, port, SocketKind::TcpConnect));
            }
            "/sockets/udp/bind" => {
                // Exercises `UdpBind` via UDP's `start-bind` (the
                // `UdpConnect` / `UdpOutgoingDatagram` socket-use
                // variants fire on `stream()` and `send()`, which are
                // fiddlier to wire through wit-bindgen 0.45; the unit
                // tests in `edge-runtime/src/socket_egress.rs` cover
                // them). Under `BlockAll` mode this returns `"deny:"`
                // from the closure; under `AllowList` it returns
                // `"allow"` because `UdpBind` is unconditionally
                // permitted (user decision documented in the plan).
                let ip = get_query_param(query, "ip").unwrap_or("127.0.0.1");
                let port: u16 = get_query_param(query, "port")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(0);
                return_text(out, 200, &socket_call_string(ip, port, SocketKind::UdpBind));
            }
            "/sockets/dns-resolve-and-connect" => {
                // Exercises `wasi:sockets/ip-name-lookup` →
                // `resolve_addresses` → `resolve_next_address` →
                // `tcp_connect`. The runtime's resolve hook (see
                // `docs/upstream-wasmtime-resolve-check.patch` and
                // `edge-runtime/src/socket_egress.rs::HostnamePinning`)
                // populates the cache during `resolve_addresses`; the
                // follow-up `start_connect` is gated by
                // `EgressPolicy::hostname_pinned_match`. Today (the
                // upstream hook not yet merged) the cache stays empty,
                // so the connect side closes the door — body
                // `"deny:access-denied"`. Once the patch merges, the
                // connect succeeds and the body is `"ok:<ip>:port"`.
                //
                // The fixture uses the local resolver (the host
                // running the worker) so the test doesn't depend on
                // a public DNS name. `host` defaults to
                // `127.0.0.1` (a literal — `resolve_addresses` parses
                // it as-is and returns it as a single IPv4 address).
                let host = get_query_param(query, "host").unwrap_or("127.0.0.1");
                let port: u16 = get_query_param(query, "port")
                    .and_then(|v| v.parse().ok())
                    .unwrap_or(80);
                return_text(
                    out,
                    200,
                    &resolve_and_connect_string(host, port),
                );
            }
            _ => {
                return_json(out, 404, br#"{"error":"not found"}"#);
            }
        }
    }
}

// ── Helpers ─────────────────────────────────────────────────────────────

fn return_json(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set("content-type", &[b"application/json".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

fn return_text(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set("content-type", &[b"text/plain".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

fn return_bytes(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set("content-type", &[b"application/octet-stream".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

/// Parse a query parameter from a query string like "key=a&val=b".
fn get_query_param<'a>(query: &'a str, name: &str) -> Option<&'a str> {
    for pair in query.split('&') {
        if let Some((k, v)) = pair.split_once('=') {
            if k == name {
                return Some(v);
            }
        }
    }
    None
}

/// Split a comma-separated value into individual strings.
/// Handles URL-encoded commas (%2C → not supported — use raw commas).
fn split_csv(s: &str) -> Vec<String> {
    if s.is_empty() {
        Vec::new()
    } else {
        s.split(',').map(|p| p.to_string()).collect()
    }
}

/// Busy loop — calibrated to exceed ~5s of Wasm execution at default
/// 1ms epoch ticks. A 100ms budget will trap this at the 10th tick.
fn return_busy_then_ok(out: ResponseOutparam) {
    let mut counter: u64 = 0;
    for i in 0u64..5_000_000_000 {
        counter = counter.wrapping_mul(31).wrapping_add(i);
    }
    core::hint::black_box(counter);
    return_json(out, 200, br#"{"slept":"~5s in Wasm"}"#);
}

// ── wasi:sockets helpers (issue #309) ───────────────────────────────────
//
// Each helper walks a wasi:sockets API and returns a response body
// describing the policy decision:
//
//   * `"allow"` — the runtime's `WasiCtxBuilder::socket_addr_check`
//     closure returned `true`. The actual TCP/UDP IO may still fail
//     (e.g. `connection-refused`) but the policy layer let it through.
//   * `"deny:<error-code-name>"` — the closure returned `false`; the
//     host impl returned `Err(error-code)`. The variant name is the
//     bindgen-discriminant of `wasi:sockets/network::ErrorCode`
//     (e.g. `"access-denied"`). The runtime traps this back to the
//     guest as a deny from the closure before any real network IO.
//
// IPv4 only — IPv6 sockets are not exercised by this fixture; the
// `is_blocked_ipv6` / `is_blocked_hostname` paths are covered by
// `edge-runtime/src/egress.rs` unit tests.

fn parse_ipv4_from_query(ip: &str) -> Option<Ipv4Address> {
    // `std::net::Ipv4Addr::from_str` rejects whitespace, edge cases, and
    // returns a `[u8; 4]` via `.octets()`. Using stdlib here avoids the
    // hand-rolled `.split('.').filter_map(parse::<u8>())` which silently
    // accepts ambiguous inputs that std rejects.
    let Ok(addr) = ip.parse::<std::net::Ipv4Addr>() else {
        return None;
    };
    let [a, b, c, d] = addr.octets();
    Some((a, b, c, d))
}

fn error_code_name(err: SockErrorCode) -> &'static str {
    match err {
        SockErrorCode::AccessDenied => "access-denied",
        SockErrorCode::AddressInUse => "address-in-use",
        SockErrorCode::AddressNotBindable => "address-not-bindable",
        SockErrorCode::ConcurrencyConflict => "concurrency-conflict",
        SockErrorCode::ConnectionAborted => "connection-aborted",
        SockErrorCode::ConnectionRefused => "connection-refused",
        SockErrorCode::ConnectionReset => "connection-reset",
        SockErrorCode::DatagramTooLarge => "datagram-too-large",
        SockErrorCode::InvalidArgument => "invalid-argument",
        SockErrorCode::InvalidState => "invalid-state",
        SockErrorCode::NameUnresolvable => "name-unresolvable",
        SockErrorCode::NewSocketLimit => "new-socket-limit",
        SockErrorCode::NotInProgress => "not-in-progress",
        SockErrorCode::NotSupported => "not-supported",
        SockErrorCode::OutOfMemory => "out-of-memory",
        SockErrorCode::PermanentResolverFailure => "permanent-resolver-failure",
        SockErrorCode::RemoteUnreachable => "remote-unreachable",
        SockErrorCode::TemporaryResolverFailure => "temporary-resolver-failure",
        SockErrorCode::Timeout => "timeout",
        SockErrorCode::Unknown => "unknown",
        SockErrorCode::WouldBlock => "would-block",
    }
}

/// Common scaffolding for the two wasi:sockets fixture paths
/// (`/sockets/tcp/connect`, `/sockets/udp/bind`). The two operations
/// diverge only in (a) which socket factory the runtime exposes
/// (`create_tcp_socket` vs `create_udp_socket`) and (b) which method
/// the socket then offers (`start_connect` vs `start_bind`). Both
/// socket types are distinct in the wit-bindgen output, so we
/// dispatch through `SocketKind` rather than a trait — keeping the
/// unification narrow and the body of each branch read like a
/// straight-line procedure.
enum SocketKind {
    TcpConnect,
    UdpBind,
}

fn socket_call_string(ip: &str, port: u16, kind: SocketKind) -> Vec<u8> {
    let address = match parse_ipv4_from_query(ip) {
        Some(a) => a,
        None => return format!("deny:invalid-ip:{ip}").into_bytes(),
    };
    let addr = IpSocketAddress::Ipv4(Ipv4SocketAddress { address, port });
    let net = instance_network();
    match kind {
        SocketKind::TcpConnect => {
            let sock = match create_tcp_socket(IpAddressFamily::Ipv4) {
                Ok(s) => s,
                Err(e) => return format!("deny:create:{}", error_code_name(e)).into_bytes(),
            };
            match sock.start_connect(&net, addr) {
                Ok(()) => b"allow".to_vec(),
                Err(e) => format!("deny:{}", error_code_name(e)).into_bytes(),
            }
        }
        SocketKind::UdpBind => {
            let sock = match create_udp_socket(IpAddressFamily::Ipv4) {
                Ok(s) => s,
                Err(e) => return format!("deny:create:{}", error_code_name(e)).into_bytes(),
            };
            match sock.start_bind(&net, addr) {
                Ok(()) => b"allow".to_vec(),
                Err(e) => format!("deny:{}", error_code_name(e)).into_bytes(),
            }
        }
    }
}

/// `wasi:sockets/ip-name-lookup.resolve_addresses` →
/// `resolve_next_address` → `tcp_connect` — exercises the runtime's
/// resolve hook (see `docs/upstream-wasmtime-resolve-check.patch`)
/// followed by the `TcpConnect` socket-use check. The flow is:
///
/// 1. Call `resolve_addresses(&net, host)`. The runtime's
///    `WasiCtxBuilder::resolve_addr_check` closure fires here; today
///    it's unset (the upstream patch hasn't merged) so the call
///    succeeds for any host the local resolver can answer.
/// 2. `resolve_next_address()` to obtain the first `IpAddress`. The
///    test asks for `AddressFamily::Ipv4` and uses the first returned
///    address; multi-address resolvers are out of scope.
/// 3. `start_connect(&net, addr)` — the runtime's
///    `WasiCtxBuilder::socket_addr_check` closure fires here. Under
///    `BlockAll` or `HostnamePinned` (empty cache, dormant) the
///    closure returns `false` and the body is
///    `"deny:access-denied"`. Under `AllowList` the body is
///    `"ok:<ip>:<port>"` if the connect succeeds (it may still fail
///    at the kernel level — `connection-refused` is a normal outcome
///    in CI; the body just becomes `"deny:connection-refused"`).
fn resolve_and_connect_string(host: &str, port: u16) -> Vec<u8> {
    let net = instance_network();
    let stream: ResolveAddressStream = match resolve_addresses(&net, host) {
        Ok(s) => s,
        Err(e) => return format!("deny:resolve:{}", error_code_name(e)).into_bytes(),
    };
    // The resolve is asynchronous in the WIT Preview 2 sense —
    // `resolve_next_address` returns `WouldBlock` until the resolver
    // has produced an address. The contract is: subscribe to the
    // stream's `Pollable`, call `wasi:io/poll::poll` on the list
    // (which blocks until at least one is ready), then call
    // `resolve_next_address` again. We loop in case the resolver
    // produces more than one address and we only need the first.
    let first = loop {
        let pollable = stream.subscribe();
        poll::poll(&[&pollable]);
        match stream.resolve_next_address() {
            Ok(Some(addr)) => break addr,
            Ok(None) => return b"deny:resolve:no-addresses".to_vec(),
            Err(SockErrorCode::WouldBlock) => continue,
            Err(e) => return format!("deny:resolve-next:{}", error_code_name(e)).into_bytes(),
        }
    };
    let ip_addr: IpSocketAddress = match first {
        crate::wasi::sockets::network::IpAddress::Ipv4(address) => {
            IpSocketAddress::Ipv4(Ipv4SocketAddress { address, port })
        }
        crate::wasi::sockets::network::IpAddress::Ipv6(_) => {
            return b"deny:resolve:ipv6-not-supported".to_vec();
        }
    };
    let sock = match create_tcp_socket(IpAddressFamily::Ipv4) {
        Ok(s) => s,
        Err(e) => return format!("deny:create:{}", error_code_name(e)).into_bytes(),
    };
    match sock.start_connect(&net, ip_addr) {
        Ok(()) => {
            // Surface a stable string so the test asserts on
            // something other than a raw "ok" — the IP the resolver
            // returned is useful for debugging.
            let ip_str = match first {
                crate::wasi::sockets::network::IpAddress::Ipv4((a, b, c, d)) => {
                    format!("{a}.{b}.{c}.{d}")
                }
                crate::wasi::sockets::network::IpAddress::Ipv6(_) => "ipv6".to_string(),
            };
            format!("ok:{ip_str}:{port}").into_bytes()
        }
        Err(e) => format!("deny:{}", error_code_name(e)).into_bytes(),
    }
}
