image: rust:1.85

stages:
  - check
  - build

rustfmt:
  stage: check
  script:
    - rustup component add rustfmt
    - cargo fmt --check --manifest-path edge-runtime/Cargo.toml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

clippy:
  stage: check
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features --manifest-path edge-runtime/Cargo.toml -- -D warnings
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
    - cargo build --manifest-path edge-runtime/Cargo.toml
    - cargo build --manifest-path edge-runtime/Cargo.toml --release
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
