//! `edge init` — scaffold a new project.
//!
//! The JS starter (`scaffold_js`) writes a `package.json` that
//! pulls `@edgecloud/sdk` from the npm registry (issue #424).
//! Earlier versions walked up from CWD looking for an in-tree
//! `edge-js-sdk/` and referenced it via `file:...` — that path
//! only worked for monorepo devs and produced a broken
//! `package.json` for everyone else. See `PACKAGE_JSON_TEMPLATE`
//! for the npm contract.
//!
//! The Rust starter (`scaffold_rust` — issue #576) writes a
//! FaaS-shaped `src/lib.rs` + `Cargo.toml` modeled on
//! `samples/hello/`, plus a vendored `wit/` tree so the project
//! builds offline outside the monorepo. The WIT tree is embedded
//! at compile time via `include_dir!`; see `crate::scaffold::wit`.

use crate::output;
use crate::LangArg;
use anyhow::Result;

/// Shared `[project]` preamble — every scaffolded `edge.toml`
/// starts with the same two-key block. The per-language tail
/// (with the correct `target` / `world` / `language` for that
/// language) is appended by `write_edge_toml` below.
const EDGE_TOML_PREAMBLE: &str = r#"[project]
name = "{name}"
version = "0.1.0"
"#;

/// Rust tail: `target = "wasm32-unknown-unknown"` (issues
/// #410/#414 — `wasm32-wasip2` direct-target emits
/// `wasi:http@0.2.4` which the wasmtime 45.0.3 linker rejects),
/// `world = "edge-runtime-handler"` (the FaaS world; required
/// by `Project` schema at `config/edgetoml.rs:38`).
const EDGE_TOML_RUST_TAIL: &str = r#"target = "wasm32-unknown-unknown"
world = "edge-runtime-handler"
language = "rust"

[deployment]
"#;

/// JS tail: `target = "wasm32-wasip2"` (correct after PR #584
/// — `edge-js-runtime` now builds directly for wasip2 and
/// emits a complete component, no adapter wrap). Same FaaS
/// world as Rust.
const EDGE_TOML_JS_TAIL: &str = r#"target = "wasm32-wasip2"
world = "edge-runtime-handler"
language = "js"

[deployment]
"#;

/// `edge.toml` body when `--api <URL>` was supplied.
const EDGE_TOML_DEPLOYMENT_WITH_API: &str = r#"api = "{api}"
"#;

// `Cargo.toml` for the Rust starter. Mirrors `samples/hello/Cargo.toml`
// exactly:
// - `[workspace]` prevents cargo from walking up to the host
//   edgeCloud workspace and failing to resolve `{name}` against the
//   host-only `edge-runtime`/`edge-cli`/`edge-worker` crates.
// - `[lib] crate-type = ["cdylib"]` + `path = "src/lib.rs"` — the
//   `wit_bindgen::generate!` macro emits `pub static` items that
//   require the `cdylib` shape (NOT `main` + `src/main.rs`).
// - `wit-bindgen = "0.45"` — pinned to match wasmtime 45.0.3's
//   `wasi:http@0.2.1` contract (issue #410). Bumping the runtime's
//   wasmtime line requires a coordinated bump here.
// - `[profile.release]` opt flags reduce the component's byte size
//   for the deploy pipeline.
const CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false
description = "edgeCloud {name} FaaS handler — generated by `edge init`"

[workspace]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
# wasmtime 45.0.3 (the runtime version this repo ships) expects a
# wasi:http@0.2.1 component, which wit-bindgen 0.45 emits.
wit-bindgen = "0.45"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
"#;

// `src/lib.rs` for the Rust starter. Mirrors `samples/hello/src/lib.rs`;
// helper bodies (`return_json`, `escape_json`) are copied verbatim.
// `path: "wit"` resolves against `CARGO_MANIFEST_DIR` at compile
// time — the canonical WIT tree is vendored into the project by
// `scaffold_rust` (via `crate::scaffold::wit::write_wit_tree`) so the
// project builds offline outside the monorepo.
//
// NOTE: wrapped in `r##"..."##` rather than `r#"..."#` because the
// body itself contains a `r#"..."#` literal (the JSON format string
// at the `format!` call below) — the inner raw delimiter would
// otherwise close the outer raw string early.
const LIB_RS_TEMPLATE: &str = r##"//! {name} — edgeCloud FaaS handler generated by `edge init`.
//!
//! Mirror of `samples/hello/src/lib.rs`. Uses `wit-bindgen`'s
//! `edge-runtime-handler` world against the vendored `./wit` tree.

#![no_main]

wit_bindgen::generate!({
    world: "edge-runtime-handler",
    path: "wit",
    generate_all,
});

use crate::edge::cloud::time;
use crate::exports::wasi::http::incoming_handler::Guest;
use crate::wasi::http::types::{
    Fields, IncomingRequest, OutgoingResponse, ResponseOutparam,
};

struct Component;
export!(Component);

// `wasi:cli/run` is part of the `edge-runtime-handler` world (it
// pulls in `wasi:cli/command`), but the host never calls it — the
// handler dispatch path goes through `wasi:http/incoming-handler`.
// We still have to provide a stub so wit-bindgen generates the export.
impl crate::exports::wasi::cli::run::Guest for Component {
    fn run() -> Result<(), ()> {
        // Unreachable in normal operation; the host dispatches per
        // request through the http handler below. If a misconfigured
        // host does call run(), returning Err makes the failure visible
        // in the host logs rather than silently exiting 0.
        Err(())
    }
}

impl Guest for Component {
    fn handle(req: IncomingRequest, out: ResponseOutparam) {
        let path = req.path_with_query().unwrap_or_else(|| "/".to_string());
        let now = time::now();
        let body = format!(
            r#"{{"hello":"world","path":"{}","now":{}}}"#,
            escape_json(&path),
            now
        );
        return_json(out, 200, body.as_bytes());
    }
}

// ── helpers (verbatim from samples/hello/src/lib.rs) ────────────────

fn return_json(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set("content-type", &[b"application/json".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

/// Escape the four characters that JSON requires (`"`, `\`, control
/// chars < 0x20). The path component of an HTTP request can contain
/// any of these; emitting unescaped bytes into a JSON document is a
/// malformed-response bug that makes the sample worse than its
/// "hello world" name suggests.
fn escape_json(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
"##;

// `package.json` for the JS starter. The SDK is pulled from npm
// (issue #424) — `edge-js-sdk/package.json` already declares
// `"name": "@edgecloud/sdk"` and `"version": "0.2.0"`, so the
// `^0.2.0` range below is the contract. The single `{name}`
// placeholder is the project name; the SDK version is fixed.
// Bumping the SDK to 0.3.0 requires a coordinated CLI template
// change + a new SDK release — see `edge-js-sdk/README.md`.
const PACKAGE_JSON_TEMPLATE: &str = r#"{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "edge build"
  },
  "dependencies": {
    "@edgecloud/sdk": "^0.2.0"
  },
  "devDependencies": {
    "esbuild": "^0.25.0"
  }
}
"#;

const JS_HANDLER_TEMPLATE: &str = r#"import { kv, time } from '@edgecloud/sdk';

/**
 * Handle an incoming HTTP request.
 * @param {{ method: string, path: string, headers: object, body: string }} req
 * @returns {{ status: number, body: string, contentType?: string }}
 */
function handleRequest(req) {
  const now = time.now();
  return {
    status: 200,
    body: JSON.stringify({
      hello: "world",
      path: req.path,
      now: Number(now),
    }),
    contentType: "application/json",
  };
}

// Export to globalThis so the runtime can call it.
globalThis.handleRequest = handleRequest;
"#;

// Active JS starter is `JS_HANDLER_TEMPLATE` above. The
// previous Javy-era `index.js` scaffold (Fetch-style
// `export async function handle(request) → Response`) was removed
// in the QuickJS pilot migration; the runtime contract is now
// `globalThis.handleRequest(req) → {status, body, contentType}`.

const GITIGNORE: &str = r#"/target/
/.wasm/
/.cargo/
.edge/
*.wasm
.DS_Store
/node_modules/
"#;

/// Scaffold a new edgeCloud project.
///
/// `api` is the optional control-plane URL written into `[deployment]`.
/// When `None`, the `[deployment]` section is left empty so the
/// runtime falls back to `EDGE_API_URL` → `~/.config/edgecloud/config.toml`
/// → `https://api.edgecloud.dev`.
///
/// `lang` selects the starter template. `Rust` (the default) writes a
/// Cargo project; `Js` writes a Javascript project using esbuild and the JS SDK.
/// The choice is persisted to `[project] language` in `edge.toml`.
pub fn run(name: &str, api: Option<&str>, lang: LangArg) -> Result<()> {
    let dir = std::path::Path::new(name);

    if dir.exists() {
        anyhow::bail!("directory '{}' already exists", name);
    }

    std::fs::create_dir_all(dir)?;

    match lang {
        LangArg::Rust => scaffold_rust(dir, name, api)?,
        LangArg::Js => scaffold_js(dir, name, api)?,
    }

    output::success(&format!("Project '{}' created", name));
    println!(
        "  cd {} && edge build{}",
        name,
        // Only emit `--lang=<x>` for non-default languages so the
        // Rust hint stays uncluttered. `as_str()` is the single
        // source of truth — adding Python or Go here would only
        // require adding the variant to `LangArg`.
        match lang {
            LangArg::Rust => String::new(),
            other => format!(" --lang={}", other.as_str()),
        }
    );
    output::hint("Next: edge auth signup  (or `edge auth login` if you already have an API key)");
    if api.is_none() {
        output::hint(
            "no --api given; edge.toml will fall back to EDGE_API_URL or \
             ~/.config/edgecloud/config.toml at deploy time",
        );
    }
    Ok(())
}

/// Rust starter: edge.toml + Cargo.toml + src/lib.rs + wit/ + .gitignore.
///
/// `wit/` is populated by `crate::scaffold::wit::write_wit_tree` (commit 2).
/// The `src/lib.rs` body wires `wit_bindgen::generate!({ path: "wit" })`
/// against the vendored tree, so the project builds offline outside the
/// monorepo. `samples/hello/` is the reference for every line here.
fn scaffold_rust(dir: &std::path::Path, name: &str, api: Option<&str>) -> Result<()> {
    write_edge_toml(dir, name, LangArg::Rust, api)?;

    let cargo_toml = CARGO_TOML_TEMPLATE.replace("{name}", name);
    std::fs::write(dir.join("Cargo.toml"), cargo_toml)?;

    let lib_rs = LIB_RS_TEMPLATE.replace("{name}", name);
    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(dir.join("src").join("lib.rs"), lib_rs)?;

    // WIT vendoring (commit 2). Kept as a no-op stub in commit 1 so
    // the template rewrite lands independently — the e2e test (commit 3)
    // asserts the `wit/` files actually appear after this returns.
    crate::scaffold::wit::write_wit_tree(dir)?;

    std::fs::write(dir.join(".gitignore"), GITIGNORE)?;
    Ok(())
}

/// JS starter: edge.toml + package.json + src/handler.js + .gitignore.
fn scaffold_js(dir: &std::path::Path, name: &str, api: Option<&str>) -> Result<()> {
    write_edge_toml(dir, name, LangArg::Js, api)?;

    // The `package.json` references `@edgecloud/sdk` from npm;
    // see the doc comment on `PACKAGE_JSON_TEMPLATE`. Monorepo
    // devs who want to test a local SDK change should use
    // `npm link edge-js-sdk/` after the scaffold — that's the
    // standard npm workflow and is not encoded here.
    let package_json = PACKAGE_JSON_TEMPLATE.replace("{name}", name);
    std::fs::write(dir.join("package.json"), package_json)?;

    std::fs::create_dir_all(dir.join("src"))?;
    std::fs::write(dir.join("src").join("handler.js"), JS_HANDLER_TEMPLATE)?;

    std::fs::write(dir.join(".gitignore"), GITIGNORE)?;
    Ok(())
}

/// Render `edge.toml` from [`EDGE_TOML_PREAMBLE`] + per-language tail
/// and write it to `<dir>/edge.toml`. Each language needs its own
/// `target` / `world` / `language` triple:
///
/// - Rust: `target = "wasm32-unknown-unknown"` (issues #410/#414),
///   `world = "edge-runtime-handler"` (FaaS world; required by the
///   `Project` schema at `config/edgetoml.rs:38`).
/// - JS: `target = "wasm32-wasip2"` (correct after PR #584 — the JS
///   runtime now builds directly for wasip2 and emits a complete
///   component, no adapter wrap needed). Same FaaS world as Rust.
///
/// Splitting into preamble + tail keeps the shared keys (`name`,
/// `version`) in one place while letting the language-specific
/// settings live with the language they describe.
fn write_edge_toml(
    dir: &std::path::Path,
    name: &str,
    lang: LangArg,
    api: Option<&str>,
) -> Result<()> {
    let mut edge_toml = EDGE_TOML_PREAMBLE.replace("{name}", name);
    let tail = match lang {
        LangArg::Rust => EDGE_TOML_RUST_TAIL,
        LangArg::Js => EDGE_TOML_JS_TAIL,
    };
    edge_toml.push_str(tail);
    if let Some(url) = api {
        edge_toml.push_str(&EDGE_TOML_DEPLOYMENT_WITH_API.replace("{api}", url));
    }
    std::fs::write(dir.join("edge.toml"), edge_toml)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    /// Render an `edge.toml` by stitching the shared preamble to the
    /// per-language tail, mirroring what `write_edge_toml` does at
    /// runtime. The two-piece shape lets each language carry its own
    /// `target` / `world` / `language` triple.
    fn render_header(name: &str, lang: super::LangArg) -> String {
        let mut s = super::EDGE_TOML_PREAMBLE.replace("{name}", name);
        let tail = match lang {
            super::LangArg::Rust => super::EDGE_TOML_RUST_TAIL,
            super::LangArg::Js => super::EDGE_TOML_JS_TAIL,
        };
        s.push_str(tail);
        s
    }

    // ── Rust starter (issue #576) ─────────────────────────────────────
    //
    // Three shape assertions per constant. Each constant is a piece
    // of the FaaS scaffold the user actually runs through, so the
    // tests pin:
    //
    //   1. the correct Rust `target` (`wasm32-unknown-unknown`, NOT
    //      `wasm32-wasip2` — issues #410/#414 show wasip2 emits
    //      `wasi:http@0.2.4` which wasmtime 45.0.3 rejects);
    //   2. the FaaS `world` (`edge-runtime-handler`, required by the
    //      `Project` schema at `config/edgetoml.rs:38`);
    //   3. `language = "rust"` so the scaffolded project is
    //      self-documenting.

    #[test]
    fn rust_header_pins_wasm32_unknown_unknown_and_world() {
        let result = render_header("myapp", super::LangArg::Rust);
        assert!(
            result.contains("target = \"wasm32-unknown-unknown\""),
            "Rust starter must target wasm32-unknown-unknown; got: {result}"
        );
        assert!(
            !result.contains("target = \"wasm32-wasip2\""),
            "Rust starter must NOT target wasm32-wasip2 (issue #410); got: {result}"
        );
        assert!(
            result.contains("world = \"edge-runtime-handler\""),
            "Rust starter must declare FaaS world; got: {result}"
        );
    }

    #[test]
    fn rust_header_includes_language_line() {
        let result = render_header("myapp", super::LangArg::Rust);
        assert!(
            result.contains(r#"language = "rust""#),
            "expected language = \"rust\" in: {result}"
        );
    }

    // ── JS starter (PR #584) ──────────────────────────────────────────

    #[test]
    fn js_header_pins_wasm32_wasip2() {
        let result = render_header("myapp", super::LangArg::Js);
        assert!(
            result.contains("target = \"wasm32-wasip2\""),
            "JS starter must keep wasm32-wasip2 (PR #584); got: {result}"
        );
        assert!(
            result.contains("world = \"edge-runtime-handler\""),
            "JS starter must declare FaaS world; got: {result}"
        );
    }

    #[test]
    fn js_header_round_trips_through_parser() {
        let result = render_header("myapp", super::LangArg::Js);
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(parsed["project"]["language"].as_str(), Some("js"));
        assert_eq!(parsed["project"]["target"].as_str(), Some("wasm32-wasip2"));
        assert_eq!(
            parsed["project"]["world"].as_str(),
            Some("edge-runtime-handler")
        );
    }

    // ── shared preamble (issue #576) ──────────────────────────────────

    #[test]
    fn edge_toml_header_valid_toml() {
        let result = render_header("myapp", super::LangArg::Rust);
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(parsed["project"]["name"].as_str(), Some("myapp"));
        assert_eq!(parsed["project"]["version"].as_str(), Some("0.1.0"));
    }

    #[test]
    fn edge_toml_with_api_section() {
        let mut result = render_header("myapp", super::LangArg::Rust);
        result.push_str(
            &super::EDGE_TOML_DEPLOYMENT_WITH_API.replace("{api}", "https://api.example.com"),
        );
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(
            parsed["deployment"]["api"].as_str(),
            Some("https://api.example.com")
        );
    }

    #[test]
    fn test_cargo_toml_template_substitution() {
        let result = super::CARGO_TOML_TEMPLATE.replace("{name}", "myapp");
        assert!(result.contains("myapp"));
        assert!(result.contains("0.1.0"));
    }

    #[test]
    fn test_cargo_toml_template_valid_toml() {
        let result = super::CARGO_TOML_TEMPLATE.replace("{name}", "myapp");
        let _: toml::Value = toml::from_str(&result).expect("invalid Cargo.toml template");
    }

    // ── Cargo.toml shape (issue #576) ─────────────────────────────────
    //
    // Pin the three things that make the Rust starter compile:
    //
    //   1. `[workspace]` so cargo does NOT walk up to the host
    //      monorepo and fail to resolve `{name}` against the
    //      host-only `edge-runtime`/`edge-cli`/`edge-worker`
    //      crates. Without this guard the user gets a confusing
    //      "failed to load manifest" error on first build.
    //   2. `[lib] crate-type = ["cdylib"]` — `wit_bindgen::generate!`
    //      emits `pub static` items that only link under the
    //      `cdylib` shape. `src/main.rs` is the wrong target.
    //   3. `wit-bindgen = "0.45"` (exact pin) — wasmtime 45.0.3
    //      expects wasi:http@0.2.1 components, which 0.45 emits.
    //      Bumping the runtime's wasmtime line requires a
    //      coordinated bump here.

    #[test]
    fn cargo_toml_template_pins_wit_bindgen_0_45_and_cdylib() {
        let result = super::CARGO_TOML_TEMPLATE;
        assert!(
            result.contains("[workspace]"),
            "Cargo.toml must declare [workspace] to block host-walkup; got:\n{result}"
        );
        assert!(
            result.contains("crate-type = [\"cdylib\"]"),
            "Cargo.toml must use cdylib crate-type (wit-bindgen emits pub statics); got:\n{result}"
        );
        assert!(
            result.contains("path = \"src/lib.rs\""),
            "Cargo.toml must point at src/lib.rs; got:\n{result}"
        );
        assert!(
            result.contains("wit-bindgen = \"0.45\""),
            "Cargo.toml must pin wit-bindgen = \"0.45\" exact; got:\n{result}"
        );
        // Defense against a future accidental bump: the pin must
        // be exact, not a `^0.45` range (which would silently pull
        // in 0.46+ once published and re-break the wasmtime contract).
        assert!(
            !result.contains("wit-bindgen = \"^0.45\""),
            "wit-bindgen pin must be exact (\"0.45\"), not caret; got:\n{result}"
        );
    }

    #[test]
    fn lib_rs_template_substitution() {
        let result = super::LIB_RS_TEMPLATE.replace("{name}", "hello-world");
        assert!(result.contains("hello-world"), "project name should appear");
        assert!(
            result.contains("#![no_main]"),
            "FaaS shape needs #![no_main]; got:\n{result}"
        );
        assert!(
            !result.contains("fn main()"),
            "src/lib.rs must NOT define fn main(); got:\n{result}"
        );
        assert!(
            result.contains("wit_bindgen::generate!"),
            "src/lib.rs must call wit_bindgen::generate!; got:\n{result}"
        );
        assert!(
            result.contains("world: \"edge-runtime-handler\""),
            "src/lib.rs must declare FaaS world; got:\n{result}"
        );
        assert!(
            result.contains("path: \"wit\""),
            "src/lib.rs must reference vendored ./wit tree; got:\n{result}"
        );
    }

    #[test]
    fn test_gitignore_contains_expected_entries() {
        let gi = super::GITIGNORE;
        assert!(gi.contains("/target/"));
        assert!(gi.contains(".edge/"));
        assert!(gi.contains(".wasm/"));
        assert!(gi.contains("*.wasm"));
    }

    // ── package.json scaffold (issue #424) ─────────────────────────
    //
    // Three pin tests on `PACKAGE_JSON_TEMPLATE`:
    //
    // 1. The npm version is `^0.2.0` and the literal `"file:"` is
    //    NOT anywhere in the template. Catches a future regression
    //    that re-introduces the path-walk fallback.
    // 2. The substituted template parses as valid JSON and the
    //    parsed `dependencies` map contains the npm reference.
    // 3. The active `JS_HANDLER_TEMPLATE` does NOT mention
    //    `wasi:http` or `Javy` — the dead `INDEX_JS_TEMPLATE`
    //    did, and any future template that re-introduces those
    //    would be a Javy-era regression.

    #[test]
    fn package_json_template_pins_npm_version_and_no_file_path() {
        // The template must reference the SDK via a semver range, not
        // a `file:...` path (the `file:` form is what broke for
        // outside-monorepo users — see issue #424).
        assert!(
            super::PACKAGE_JSON_TEMPLATE.contains(r#""@edgecloud/sdk": "^0.2.0""#),
            "expected pinned npm version ^0.2.0 in PACKAGE_JSON_TEMPLATE; got: {}",
            super::PACKAGE_JSON_TEMPLATE
        );
        assert!(
            !super::PACKAGE_JSON_TEMPLATE.contains("file:"),
            "PACKAGE_JSON_TEMPLATE must not reference the SDK via a file: path (issue #424); got: {}",
            super::PACKAGE_JSON_TEMPLATE
        );
    }

    #[test]
    fn package_json_template_round_trips_through_parser() {
        let result = super::PACKAGE_JSON_TEMPLATE.replace("{name}", "myapp");
        let parsed: serde_json::Value =
            serde_json::from_str(&result).expect("PACKAGE_JSON_TEMPLATE must be valid JSON");
        assert_eq!(parsed["name"], "myapp");
        assert_eq!(
            parsed["dependencies"]["@edgecloud/sdk"], "^0.2.0",
            "expected npm version range in parsed dependencies"
        );
        // `serde_json` is already in scope via other CLI code paths;
        // the test surface keeps the dependency visible to anyone
        // touching this template.
    }

    #[test]
    fn js_handler_template_does_not_import_javy_runtime() {
        // The active scaffold is the QuickJS contract
        // (`globalThis.handleRequest(req) → {status, body, contentType}`).
        // It must NOT mention `wasi:http` directly (that's the
        // host-side binding the runtime injects), and it must NOT
        // mention Javy (the previous runtime the JS pilot replaced).
        assert!(
            !super::JS_HANDLER_TEMPLATE.contains("wasi:http"),
            "JS_HANDLER_TEMPLATE must not reference wasi:http directly; got: {}",
            super::JS_HANDLER_TEMPLATE
        );
        assert!(
            !super::JS_HANDLER_TEMPLATE.contains("Javy"),
            "JS_HANDLER_TEMPLATE must not mention Javy; got: {}",
            super::JS_HANDLER_TEMPLATE
        );
    }
}
