//! CLI commands.

pub mod activate;
pub mod apps;
pub mod auth;
pub mod billing;
pub mod build;
pub mod completions;
pub mod deploy;
pub mod deployments;
pub mod dev;
pub mod domains;
pub mod egress;
pub mod env;
pub mod ingress;
pub mod init;
pub mod logs;
pub mod migrate;
pub mod open;
pub mod quota;
pub mod rollback;
pub(crate) mod state_io;
pub mod status;
pub mod traffic;
