//! Scaffold template strings (issue #576).
//!
//! Every `edge init` artifact is a literal here. Splitting them out
//! from `crate::commands::init` keeps the procedural code (write
//! `edge.toml`, write `Cargo.toml`, run `write_wit_tree`, …) in one
//! place and the strings — with their tests — in another. The tests
//! pin the templates' shape so a regression that introduces stray
//! whitespace or a quoting typo surfaces here, not as a downstream
//! linker error or a malformed `package.json`.
//!
//! The split landed as review finding on PR #589: keeping all nine
//! constants + the `render_header` helper inline in `init.rs` pushed
//! that file to 666 lines and muddled the boundary between "what
//! bytes does the scaffold write" and "what filesystem moves does
//! the scaffold make."

use crate::LangArg;

/// Shared `[project]` preamble — every scaffolded `edge.toml`
/// starts with the same two-key block. The per-language tail
/// (with the correct `target` / `world` / `language` for that
/// language) is appended by `write_edge_toml` below.
pub const EDGE_TOML_PREAMBLE: &str = r#"[project]
name = "{name}"
version = "0.1.0"
"#;

/// Rust tail: `target = "wasm32-unknown-unknown"` (issues
/// #410/#414 — `wasm32-wasip2` direct-target emits
/// `wasi:http@0.2.4` which the wasmtime 45.0.3 linker rejects),
/// `world = "edge-runtime-handler"` (the FaaS world; required
/// by `Project` schema at `config/edgetoml.rs:38`).
pub const EDGE_TOML_RUST_TAIL: &str = r#"target = "wasm32-unknown-unknown"
world = "edge-runtime-handler"
language = "rust"

[deployment]
"#;

/// JS tail: `target = "wasm32-wasip2"` (correct after PR #584
/// — `edge-js-runtime` now builds directly for wasip2 and
/// emits a complete component, no adapter wrap). Same FaaS
/// world as Rust.
pub const EDGE_TOML_JS_TAIL: &str = r#"target = "wasm32-wasip2"
world = "edge-runtime-handler"
language = "js"

[deployment]
"#;

/// `edge.toml` body when `--api <URL>` was supplied.
pub const EDGE_TOML_DEPLOYMENT_WITH_API: &str = r#"api = "{api}"
"#;

// `Cargo.toml` for the Rust starter. Mirrors `samples/hello/Cargo.toml`
// exactly:
// - `[workspace]` prevents cargo from walking up to the host
//   edgeCloud workspace and failing to resolve `{name}` against the
//   host-only `edge-runtime`/`edge-cli`/`edge-worker` crates.
// - `[lib] crate-type = ["cdylib"]` + `path = "src/lib.rs"` — the
//   `wit_bindgen::generate!` macro emits `pub static` items that
//   require the `cdylib` shape (NOT `main` + `src/main.rs`).
// - `wit-bindgen = "0.45"` — pinned to match wasmtime 45.0.3's
//   `wasi:http@0.2.1` contract (issue #410). Bumping the runtime's
//   wasmtime line requires a coordinated bump here.
// - `[profile.release]` opt flags reduce the component's byte size
//   for the deploy pipeline.
pub const CARGO_TOML_TEMPLATE: &str = r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"
publish = false
description = "edgeCloud {name} FaaS handler — generated by `edge init`"

[workspace]

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
# wasmtime 45.0.3 (the runtime version this repo ships) expects a
# wasi:http@0.2.1 component, which wit-bindgen 0.45 emits.
wit-bindgen = "0.45"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
"#;

// `src/lib.rs` for the Rust starter. Mirrors `samples/hello/src/lib.rs`;
// helper bodies (`return_json`, `escape_json`) are copied verbatim.
// `path: "wit"` resolves against `CARGO_MANIFEST_DIR` at compile
// time — the canonical WIT tree is vendored into the project by
// `scaffold_rust` (via `crate::scaffold::wit::write_wit_tree`) so the
// project builds offline outside the monorepo.
//
// NOTE: wrapped in `r##"..."##` rather than `r#"..."#` because the
// body itself contains a `r#"..."#` literal (the JSON format string
// at the `format!` call below) — the inner raw delimiter would
// otherwise close the outer raw string early.
pub const LIB_RS_TEMPLATE: &str = r##"//! {name} — edgeCloud FaaS handler generated by `edge init`.
//!
//! Mirror of `samples/hello/src/lib.rs`. Uses `wit-bindgen`'s
//! `edge-runtime-handler` world against the vendored `./wit` tree.

#![no_main]

wit_bindgen::generate!({
    world: "edge-runtime-handler",
    path: "wit",
    generate_all,
});

use crate::edge::cloud::time;
use crate::exports::wasi::http::incoming_handler::Guest;
use crate::wasi::http::types::{
    Fields, IncomingRequest, OutgoingResponse, ResponseOutparam,
};

struct Component;
export!(Component);

// `wasi:cli/run` is part of the `edge-runtime-handler` world (it
// pulls in `wasi:cli/command`), but the host never calls it — the
// handler dispatch path goes through `wasi:http/incoming-handler`.
// We still have to provide a stub so wit-bindgen generates the export.
impl crate::exports::wasi::cli::run::Guest for Component {
    fn run() -> Result<(), ()> {
        // Unreachable in normal operation; the host dispatches per
        // request through the http handler below. If a misconfigured
        // host does call run(), returning Err makes the failure visible
        // in the host logs rather than silently exiting 0.
        Err(())
    }
}

impl Guest for Component {
    fn handle(req: IncomingRequest, out: ResponseOutparam) {
        let path = req.path_with_query().unwrap_or_else(|| "/".to_string());
        let now = time::now();
        let body = format!(
            r#"{{"hello":"world","path":"{}","now":{}}}"#,
            escape_json(&path),
            now
        );
        return_json(out, 200, body.as_bytes());
    }
}

// ── helpers (verbatim from samples/hello/src/lib.rs) ────────────────

fn return_json(out: ResponseOutparam, status: u16, body: &[u8]) {
    let headers = Fields::new();
    let _ = headers.set("content-type", &[b"application/json".to_vec()]);
    let resp = OutgoingResponse::new(headers);
    resp.set_status_code(status).unwrap();
    let body_handle = resp.body().expect("response body");
    let stream = body_handle.write().expect("output stream");
    stream.blocking_write_and_flush(body).unwrap();
    drop(stream);
    let _ = crate::wasi::http::types::OutgoingBody::finish(body_handle, None);
    crate::wasi::http::types::ResponseOutparam::set(out, Ok(resp));
}

/// Escape the four characters that JSON requires (`"`, `\`, control
/// chars < 0x20). The path component of an HTTP request can contain
/// any of these; emitting unescaped bytes into a JSON document is a
/// malformed-response bug that makes the sample worse than its
/// "hello world" name suggests.
fn escape_json(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04x}", c as u32)),
            c => out.push(c),
        }
    }
    out
}
"##;

// `package.json` for the JS starter. The SDK is pulled from npm
// (issue #424) — `edge-js-sdk/package.json` already declares
// `"name": "@edgecloud/sdk"` and `"version": "0.2.0"`, so the
// `^0.2.0` range below is the contract. The single `{name}`
// placeholder is the project name; the SDK version is fixed.
// Bumping the SDK to 0.3.0 requires a coordinated CLI template
// change + a new SDK release — see `edge-js-sdk/README.md`.
pub const PACKAGE_JSON_TEMPLATE: &str = r#"{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "edge build"
  },
  "dependencies": {
    "@edgecloud/sdk": "^0.2.0"
  },
  "devDependencies": {
    "esbuild": "^0.25.0"
  }
}
"#;

pub const JS_HANDLER_TEMPLATE: &str = r#"import { kv, time } from '@edgecloud/sdk';

/**
 * Handle an incoming HTTP request.
 * @param {{ method: string, path: string, headers: object, body: string }} req
 * @returns {{ status: number, body: string, contentType?: string }}
 */
function handleRequest(req) {
  const now = time.now();
  return {
    status: 200,
    body: JSON.stringify({
      hello: "world",
      path: req.path,
      now: Number(now),
    }),
    contentType: "application/json",
  };
}

// Export to globalThis so the runtime can call it.
globalThis.handleRequest = handleRequest;
"#;

// Active JS starter is `JS_HANDLER_TEMPLATE` above. The
// previous Javy-era `index.js` scaffold (Fetch-style
// `export async function handle(request) → Response`) was removed
// in the QuickJS pilot migration; the runtime contract is now
// `globalThis.handleRequest(req) → {status, body, contentType}`.

pub const GITIGNORE: &str = r#"/target/
/.wasm/
/.cargo/
.edge/
*.wasm
.DS_Store
/node_modules/
"#;

/// Render an `edge.toml` by stitching the shared preamble to the
/// per-language tail. Mirrors what `crate::commands::init::write_edge_toml`
/// does at runtime — duplicated here so the tests can exercise the
/// shape without standing up a tempdir. The two-piece shape lets
/// each language carry its own `target` / `world` / `language`
/// triple while keeping the shared `name` / `version` keys in one
/// place.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) fn render_header(name: &str, lang: LangArg) -> String {
    let mut s = EDGE_TOML_PREAMBLE.replace("{name}", name);
    let tail = match lang {
        LangArg::Rust => EDGE_TOML_RUST_TAIL,
        LangArg::Js => EDGE_TOML_JS_TAIL,
    };
    s.push_str(tail);
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Rust starter (issue #576) ─────────────────────────────────────
    //
    // Three shape assertions per constant. Each constant is a piece
    // of the FaaS scaffold the user actually runs through, so the
    // tests pin:
    //
    //   1. the correct Rust `target` (`wasm32-unknown-unknown`, NOT
    //      `wasm32-wasip2` — issues #410/#414 show wasip2 emits
    //      `wasi:http@0.2.4` which wasmtime 45.0.3 rejects);
    //   2. the FaaS `world` (`edge-runtime-handler`, required by the
    //      `Project` schema at `config/edgetoml.rs:38`);
    //   3. `language = "rust"` so the scaffolded project is
    //      self-documenting.

    #[test]
    fn rust_header_pins_wasm32_unknown_unknown_and_world() {
        let result = render_header("myapp", LangArg::Rust);
        assert!(
            result.contains("target = \"wasm32-unknown-unknown\""),
            "Rust starter must target wasm32-unknown-unknown; got: {result}"
        );
        assert!(
            !result.contains("target = \"wasm32-wasip2\""),
            "Rust starter must NOT target wasm32-wasip2 (issue #410); got: {result}"
        );
        assert!(
            result.contains("world = \"edge-runtime-handler\""),
            "Rust starter must declare FaaS world; got: {result}"
        );
    }

    #[test]
    fn rust_header_includes_language_line() {
        let result = render_header("myapp", LangArg::Rust);
        assert!(
            result.contains(r#"language = "rust""#),
            "expected language = \"rust\" in: {result}"
        );
    }

    // ── JS starter (PR #584) ──────────────────────────────────────────

    #[test]
    fn js_header_pins_wasm32_wasip2() {
        let result = render_header("myapp", LangArg::Js);
        assert!(
            result.contains("target = \"wasm32-wasip2\""),
            "JS starter must keep wasm32-wasip2 (PR #584); got: {result}"
        );
        assert!(
            result.contains("world = \"edge-runtime-handler\""),
            "JS starter must declare FaaS world; got: {result}"
        );
    }

    #[test]
    fn js_header_round_trips_through_parser() {
        let result = render_header("myapp", LangArg::Js);
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(parsed["project"]["language"].as_str(), Some("js"));
        assert_eq!(parsed["project"]["target"].as_str(), Some("wasm32-wasip2"));
        assert_eq!(
            parsed["project"]["world"].as_str(),
            Some("edge-runtime-handler")
        );
    }

    /// Rust counterpart — the `*_pins_*` tests above check that the
    /// literal strings appear in the rendered TOML, but a regression
    /// that introduced stray whitespace or a quoting typo could keep
    /// the substring match intact while producing invalid TOML. This
    /// test parses the rendered output and pulls the language /
    /// target / world fields back out, so the contract that the
    /// `Project` schema parses it holds for Rust as well as JS.
    /// See `config/edgetoml.rs:38` for the world field's
    /// required-ness and `config/edgetoml.rs:61` for the default
    /// target that `Project::default_target` falls back to.
    #[test]
    fn rust_header_round_trips_through_parser() {
        let result = render_header("myapp", LangArg::Rust);
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(parsed["project"]["language"].as_str(), Some("rust"));
        assert_eq!(
            parsed["project"]["target"].as_str(),
            Some("wasm32-unknown-unknown")
        );
        assert_eq!(
            parsed["project"]["world"].as_str(),
            Some("edge-runtime-handler")
        );
    }

    // ── shared preamble (issue #576) ──────────────────────────────────

    #[test]
    fn edge_toml_header_valid_toml() {
        let result = render_header("myapp", LangArg::Rust);
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(parsed["project"]["name"].as_str(), Some("myapp"));
        assert_eq!(parsed["project"]["version"].as_str(), Some("0.1.0"));
    }

    #[test]
    fn edge_toml_with_api_section() {
        let mut result = render_header("myapp", LangArg::Rust);
        result.push_str(&EDGE_TOML_DEPLOYMENT_WITH_API.replace("{api}", "https://api.example.com"));
        let parsed: toml::Value = toml::from_str(&result).expect("invalid TOML");
        assert_eq!(
            parsed["deployment"]["api"].as_str(),
            Some("https://api.example.com")
        );
    }

    #[test]
    fn test_cargo_toml_template_substitution() {
        let result = CARGO_TOML_TEMPLATE.replace("{name}", "myapp");
        assert!(result.contains("myapp"));
        assert!(result.contains("0.1.0"));
    }

    #[test]
    fn test_cargo_toml_template_valid_toml() {
        let result = CARGO_TOML_TEMPLATE.replace("{name}", "myapp");
        let _: toml::Value = toml::from_str(&result).expect("invalid Cargo.toml template");
    }

    // ── Cargo.toml shape (issue #576) ─────────────────────────────────
    //
    // Pin the three things that make the Rust starter compile:
    //
    //   1. `[workspace]` so cargo does NOT walk up to the host
    //      monorepo and fail to resolve `{name}` against the
    //      host-only `edge-runtime`/`edge-cli`/`edge-worker`
    //      crates. Without this guard the user gets a confusing
    //      "failed to load manifest" error on first build.
    //   2. `[lib] crate-type = ["cdylib"]` — `wit_bindgen::generate!`
    //      emits `pub static` items that only link under the
    //      `cdylib` shape. `src/main.rs` is the wrong target.
    //   3. `wit-bindgen = "0.45"` (exact pin) — wasmtime 45.0.3
    //      expects wasi:http@0.2.1 components, which 0.45 emits.
    //      Bumping the runtime's wasmtime line requires a
    //      coordinated bump here.

    #[test]
    fn cargo_toml_template_pins_wit_bindgen_0_45_and_cdylib() {
        let result = CARGO_TOML_TEMPLATE;
        assert!(
            result.contains("[workspace]"),
            "Cargo.toml must declare [workspace] to block host-walkup; got:\n{result}"
        );
        assert!(
            result.contains("crate-type = [\"cdylib\"]"),
            "Cargo.toml must use cdylib crate-type (wit-bindgen emits pub statics); got:\n{result}"
        );
        assert!(
            result.contains("path = \"src/lib.rs\""),
            "Cargo.toml must point at src/lib.rs; got:\n{result}"
        );
        assert!(
            result.contains("wit-bindgen = \"0.45\""),
            "Cargo.toml must pin wit-bindgen = \"0.45\" exact; got:\n{result}"
        );
        // Defense against a future accidental bump: the pin must
        // be exact, not a `^0.45` range (which would silently pull
        // in 0.46+ once published and re-break the wasmtime contract).
        assert!(
            !result.contains("wit-bindgen = \"^0.45\""),
            "wit-bindgen pin must be exact (\"0.45\"), not caret; got:\n{result}"
        );
    }

    #[test]
    fn lib_rs_template_substitution() {
        let result = LIB_RS_TEMPLATE.replace("{name}", "hello-world");
        assert!(result.contains("hello-world"), "project name should appear");
        assert!(
            result.contains("#![no_main]"),
            "FaaS shape needs #![no_main]; got:\n{result}"
        );
        assert!(
            !result.contains("fn main()"),
            "src/lib.rs must NOT define fn main(); got:\n{result}"
        );
        assert!(
            result.contains("wit_bindgen::generate!"),
            "src/lib.rs must call wit_bindgen::generate!; got:\n{result}"
        );
        assert!(
            result.contains("world: \"edge-runtime-handler\""),
            "src/lib.rs must declare FaaS world; got:\n{result}"
        );
        assert!(
            result.contains("path: \"wit\""),
            "src/lib.rs must reference vendored ./wit tree; got:\n{result}"
        );
    }

    #[test]
    fn test_gitignore_contains_expected_entries() {
        let gi = GITIGNORE;
        assert!(gi.contains("/target/"));
        assert!(gi.contains(".edge/"));
        assert!(gi.contains(".wasm/"));
        assert!(gi.contains("*.wasm"));
    }

    // ── package.json scaffold (issue #424) ─────────────────────────
    //
    // Three pin tests on `PACKAGE_JSON_TEMPLATE`:
    //
    // 1. The npm version is `^0.2.0` and the literal `"file:"` is
    //    NOT anywhere in the template. Catches a future regression
    //    that re-introduces the path-walk fallback.
    // 2. The substituted template parses as valid JSON and the
    //    parsed `dependencies` map contains the npm reference.
    // 3. The active `JS_HANDLER_TEMPLATE` does NOT mention
    //    `wasi:http` or `Javy` — the dead `INDEX_JS_TEMPLATE`
    //    did, and any future template that re-introduces those
    //    would be a Javy-era regression.

    #[test]
    fn package_json_template_pins_npm_version_and_no_file_path() {
        // The template must reference the SDK via a semver range, not
        // a `file:...` path (the `file:` form is what broke for
        // outside-monorepo users — see issue #424).
        assert!(
            PACKAGE_JSON_TEMPLATE.contains(r#""@edgecloud/sdk": "^0.2.0""#),
            "expected pinned npm version ^0.2.0 in PACKAGE_JSON_TEMPLATE; got: {}",
            PACKAGE_JSON_TEMPLATE
        );
        assert!(
            !PACKAGE_JSON_TEMPLATE.contains("file:"),
            "PACKAGE_JSON_TEMPLATE must not reference the SDK via a file: path (issue #424); got: {}",
            PACKAGE_JSON_TEMPLATE
        );
    }

    #[test]
    fn package_json_template_round_trips_through_parser() {
        let result = PACKAGE_JSON_TEMPLATE.replace("{name}", "myapp");
        let parsed: serde_json::Value =
            serde_json::from_str(&result).expect("PACKAGE_JSON_TEMPLATE must be valid JSON");
        assert_eq!(parsed["name"], "myapp");
        assert_eq!(
            parsed["dependencies"]["@edgecloud/sdk"], "^0.2.0",
            "expected npm version range in parsed dependencies"
        );
        // `serde_json` is already in scope via other CLI code paths;
        // the test surface keeps the dependency visible to anyone
        // touching this template.
    }

    #[test]
    fn js_handler_template_does_not_import_javy_runtime() {
        // The active scaffold is the QuickJS contract
        // (`globalThis.handleRequest(req) → {status, body, contentType}`).
        // It must NOT mention `wasi:http` directly (that's the
        // host-side binding the runtime injects), and it must NOT
        // mention Javy (the previous runtime the JS pilot replaced).
        assert!(
            !JS_HANDLER_TEMPLATE.contains("wasi:http"),
            "JS_HANDLER_TEMPLATE must not reference wasi:http directly; got: {}",
            JS_HANDLER_TEMPLATE
        );
        assert!(
            !JS_HANDLER_TEMPLATE.contains("Javy"),
            "JS_HANDLER_TEMPLATE must not mention Javy; got: {}",
            JS_HANDLER_TEMPLATE
        );
    }
}
